/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author edmun
 */
public class tela_inicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form tela_inicio
     */
    public tela_inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelControle = new javax.swing.JPanel();
        lbl_15 = new javax.swing.JLabel();
        lbl_4 = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        lbl_3 = new javax.swing.JLabel();
        lbl_5 = new javax.swing.JLabel();
        lbl_6 = new javax.swing.JLabel();
        lbl_8 = new javax.swing.JLabel();
        lbl_9 = new javax.swing.JLabel();
        lbl_7 = new javax.swing.JLabel();
        lbl_11 = new javax.swing.JLabel();
        lbl_10 = new javax.swing.JLabel();
        lbl_13 = new javax.swing.JLabel();
        lbl_12 = new javax.swing.JLabel();
        lbl_14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jrbtt_funcionario = new javax.swing.JRadioButton();
        jrbtt_dependente = new javax.swing.JRadioButton();
        jrbtt_livro = new javax.swing.JRadioButton();
        jbtt_mostrar = new javax.swing.JButton();
        jlbl_boasVindas = new javax.swing.JLabel();
        lbl_16 = new javax.swing.JLabel();

        lbl_15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_15.setText("Saiba como usar o sistema de forma fácil é rápida");

        lbl_4.setText("as infomações necessarias.");

        lbl_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_1.setText("Saiba como usar o sistema de forma fácil é rápida");

        lbl_2.setText("Passo 1: Na parte superior do sistema você verá uma barra de menu contendo as funcionalidades do sistema.");

        lbl_3.setText("Passo 2: Caso você queira cadastrar um funcionário, clique em Cadastrar Funcionário e em seguida preencha ");

        lbl_5.setText("Passo 3: Caso você queria cadastrar um dependente, clique em Cadastrar Dependente e em seguida peencha ");

        lbl_6.setText("com as informações necessarias.");

        lbl_8.setText("informações necessarias.");

        lbl_9.setText("Passo 5: Caso você queria pegar emprestado um livro, clique em Emprestimo e em seguida peencha com as ");

        lbl_7.setText("Passo 4: Caso você queria cadastrar um livro, clique em Cadastrar Livro e em seguida peencha com as ");

        lbl_11.setText("Passo 6: Caso você queria pegar devolver um livro, clique em Devolução e em seguida peencha com as ");

        lbl_10.setText("com as informações necessarias.");

        lbl_13.setText("Passo 7: Caso você queria apenas visualizar os cadastros feitos tanto de funcionario, dependente ou livro");

        lbl_12.setText("informações necessarias.");

        lbl_14.setText("basta clicar em Visualização e escolher qual tabela você deseja ver.");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setText("- Nome Completo");

        jLabel18.setText("- CPF");

        jLabel19.setText("- Cargo");

        jLabel20.setText("- Data de Nascimento");

        jLabel21.setText("- Telefone");

        jLabel22.setText("- Endereço Completo");

        jLabel23.setText("- Gênero");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Lista");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel23)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jrbtt_funcionario.setText("Informações Funcionario");

        jrbtt_dependente.setText("Informações Dependentes");

        jrbtt_livro.setText("Informações Livros");
        jrbtt_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtt_livroActionPerformed(evt);
            }
        });

        jbtt_mostrar.setText("MOSTRAR");

        jlbl_boasVindas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlbl_boasVindas.setText("Seja bem vindo ao Software de empréstimo de livros.");

        javax.swing.GroupLayout panelControleLayout = new javax.swing.GroupLayout(panelControle);
        panelControle.setLayout(panelControleLayout);
        panelControleLayout.setHorizontalGroup(
            panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControleLayout.createSequentialGroup()
                .addGroup(panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jlbl_boasVindas))
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_15)
                            .addComponent(lbl_1)))
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_2)
                            .addComponent(lbl_3)
                            .addComponent(lbl_4)
                            .addComponent(lbl_5)
                            .addComponent(lbl_6)
                            .addComponent(lbl_7)
                            .addComponent(lbl_8)
                            .addComponent(lbl_9))
                        .addGap(75, 75, 75)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lbl_10)
                        .addGap(479, 479, 479)
                        .addComponent(jrbtt_funcionario))
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lbl_11)
                        .addGap(106, 106, 106)
                        .addComponent(jrbtt_dependente))
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lbl_12)
                        .addGap(520, 520, 520)
                        .addComponent(jrbtt_livro))
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lbl_13)
                        .addGap(132, 132, 132)
                        .addComponent(jbtt_mostrar))
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lbl_14)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelControleLayout.setVerticalGroup(
            panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControleLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jlbl_boasVindas)
                .addGap(6, 6, 6)
                .addGroup(panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_15)
                    .addComponent(lbl_1))
                .addGap(32, 32, 32)
                .addGroup(panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addComponent(lbl_2)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_3)
                        .addGap(6, 6, 6)
                        .addComponent(lbl_4)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_5)
                        .addGap(6, 6, 6)
                        .addComponent(lbl_6)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_7)
                        .addGap(6, 6, 6)
                        .addComponent(lbl_8)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_9))
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lbl_10))
                    .addComponent(jrbtt_funcionario))
                .addGap(9, 9, 9)
                .addGroup(panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_11))
                    .addComponent(jrbtt_dependente))
                .addGap(5, 5, 5)
                .addGroup(panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lbl_12))
                    .addComponent(jrbtt_livro))
                .addGap(9, 9, 9)
                .addGroup(panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControleLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lbl_13))
                    .addComponent(jbtt_mostrar))
                .addGap(4, 4, 4)
                .addComponent(lbl_14)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        lbl_16.setText("Passo 1: Na parte superior do sistema você verá uma barra de menu contendo as funcionalidades do sistema.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(173, 173, 173)
                    .addComponent(lbl_16)
                    .addContainerGap(173, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(277, 277, 277)
                    .addComponent(lbl_16)
                    .addContainerGap(277, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtt_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtt_livroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtt_livroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtt_mostrar;
    private javax.swing.JLabel jlbl_boasVindas;
    private javax.swing.JRadioButton jrbtt_dependente;
    private javax.swing.JRadioButton jrbtt_funcionario;
    private javax.swing.JRadioButton jrbtt_livro;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_10;
    private javax.swing.JLabel lbl_11;
    private javax.swing.JLabel lbl_12;
    private javax.swing.JLabel lbl_13;
    private javax.swing.JLabel lbl_14;
    private javax.swing.JLabel lbl_15;
    private javax.swing.JLabel lbl_16;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_4;
    private javax.swing.JLabel lbl_5;
    private javax.swing.JLabel lbl_6;
    private javax.swing.JLabel lbl_7;
    private javax.swing.JLabel lbl_8;
    private javax.swing.JLabel lbl_9;
    private javax.swing.JPanel panelControle;
    // End of variables declaration//GEN-END:variables
}
