/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author edmun
 */
public class tela_inicial extends javax.swing.JFrame {

    /**
     * Creates new form tela_inicial
     */
    public tela_inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        painelControle = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmn_cdtr_funcionario = new javax.swing.JMenu();
        jm_cdtr_livro = new javax.swing.JMenu();
        jm_cdtr_dependente = new javax.swing.JMenu();
        jm_devolucao = new javax.swing.JMenu();
        jm_emprestimo = new javax.swing.JMenu();
        jm_visualizacao = new javax.swing.JMenu();
        jmit_visuFuncionario = new javax.swing.JMenuItem();
        jmit_visuDependente = new javax.swing.JMenuItem();
        jmit_visuLivro = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(922, 590));

        painelControle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setText("Inicio");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jmn_cdtr_funcionario.setText("Cadastrar Funcionario");
        jmn_cdtr_funcionario.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jmn_cdtr_funcionarioMenuSelected(evt);
            }
        });
        jmn_cdtr_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmn_cdtr_funcionarioActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmn_cdtr_funcionario);

        jm_cdtr_livro.setText("Cadastrar Livro");
        jMenuBar1.add(jm_cdtr_livro);

        jm_cdtr_dependente.setText("Cadastrar Dependente");
        jMenuBar1.add(jm_cdtr_dependente);

        jm_devolucao.setText("Devolução");
        jMenuBar1.add(jm_devolucao);

        jm_emprestimo.setText("Empréstimo");
        jMenuBar1.add(jm_emprestimo);

        jm_visualizacao.setText("Visualização");

        jmit_visuFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmit_visuFuncionario.setText("Tabela Funcionário");
        jmit_visuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmit_visuFuncionarioActionPerformed(evt);
            }
        });
        jm_visualizacao.add(jmit_visuFuncionario);

        jmit_visuDependente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmit_visuDependente.setText("Tabela Dependente");
        jm_visualizacao.add(jmit_visuDependente);

        jmit_visuLivro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmit_visuLivro.setText("Tabela Livro");
        jm_visualizacao.add(jmit_visuLivro);

        jMenuBar1.add(jm_visualizacao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelControle)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelControle)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmit_visuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmit_visuFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmit_visuFuncionarioActionPerformed

    private void jmn_cdtr_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmn_cdtr_funcionarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmn_cdtr_funcionarioActionPerformed

    private void jmn_cdtr_funcionarioMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmn_cdtr_funcionarioMenuSelected
        // TODO add your handling code here:
        tela_cdtr_funcionarioOne frameOne = new tela_cdtr_funcionarioOne();
        painelControle.add(frameOne);
        frameOne.setVisible(true);
        
    }//GEN-LAST:event_jmn_cdtr_funcionarioMenuSelected

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        tela_inicio fra = new tela_inicio();
        painelControle.add(fra);
        fra.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jm_cdtr_dependente;
    private javax.swing.JMenu jm_cdtr_livro;
    private javax.swing.JMenu jm_devolucao;
    private javax.swing.JMenu jm_emprestimo;
    private javax.swing.JMenu jm_visualizacao;
    private javax.swing.JMenuItem jmit_visuDependente;
    private javax.swing.JMenuItem jmit_visuFuncionario;
    private javax.swing.JMenuItem jmit_visuLivro;
    private javax.swing.JMenu jmn_cdtr_funcionario;
    private javax.swing.JDesktopPane painelControle;
    // End of variables declaration//GEN-END:variables
}
